// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "webhook-dispatcher/internal/pkg/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FetchDueRetries provides a mock function with given fields: ctx, limit, now
func (_m *MockRepository) FetchDueRetries(ctx context.Context, limit int64, now time.Time) ([]domain.Event, error) {
	ret := _m.Called(ctx, limit, now)

	if len(ret) == 0 {
		panic("no return value specified for FetchDueRetries")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) ([]domain.Event, error)); ok {
		return rf(ctx, limit, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) []domain.Event); ok {
		r0 = rf(ctx, limit, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = rf(ctx, limit, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FetchDueRetries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDueRetries'
type MockRepository_FetchDueRetries_Call struct {
	*mock.Call
}

// FetchDueRetries is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
//   - now time.Time
func (_e *MockRepository_Expecter) FetchDueRetries(ctx interface{}, limit interface{}, now interface{}) *MockRepository_FetchDueRetries_Call {
	return &MockRepository_FetchDueRetries_Call{Call: _e.mock.On("FetchDueRetries", ctx, limit, now)}
}

func (_c *MockRepository_FetchDueRetries_Call) Run(run func(ctx context.Context, limit int64, now time.Time)) *MockRepository_FetchDueRetries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Time))
	})
	return _c
}

func (_c *MockRepository_FetchDueRetries_Call) Return(_a0 []domain.Event, _a1 error) *MockRepository_FetchDueRetries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FetchDueRetries_Call) RunAndReturn(run func(context.Context, int64, time.Time) ([]domain.Event, error)) *MockRepository_FetchDueRetries_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPending provides a mock function with given fields: ctx, ids
func (_m *MockRepository) MarkPending(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkPending")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPending'
type MockRepository_MarkPending_Call struct {
	*mock.Call
}

// MarkPending is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockRepository_Expecter) MarkPending(ctx interface{}, ids interface{}) *MockRepository_MarkPending_Call {
	return &MockRepository_MarkPending_Call{Call: _e.mock.On("MarkPending", ctx, ids)}
}

func (_c *MockRepository_MarkPending_Call) Run(run func(ctx context.Context, ids []string)) *MockRepository_MarkPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRepository_MarkPending_Call) Return(_a0 error) *MockRepository_MarkPending_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkPending_Call) RunAndReturn(run func(context.Context, []string) error) *MockRepository_MarkPending_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
