// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "webhook-dispatcher/internal/pkg/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// FindWebhook provides a mock function with given fields: ctx, id
func (_m *MockRepository) FindWebhook(ctx context.Context, id string) (domain.Webhook, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindWebhook")
	}

	var r0 domain.Webhook
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Webhook, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Webhook); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Webhook)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWebhook'
type MockRepository_FindWebhook_Call struct {
	*mock.Call
}

// FindWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindWebhook(ctx interface{}, id interface{}) *MockRepository_FindWebhook_Call {
	return &MockRepository_FindWebhook_Call{Call: _e.mock.On("FindWebhook", ctx, id)}
}

func (_c *MockRepository_FindWebhook_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindWebhook_Call) Return(_a0 domain.Webhook, _a1 error) *MockRepository_FindWebhook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindWebhook_Call) RunAndReturn(run func(context.Context, string) (domain.Webhook, error)) *MockRepository_FindWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// MarkEventPoison provides a mock function with given fields: ctx, eventID, attempt
func (_m *MockRepository) MarkEventPoison(ctx context.Context, eventID string, attempt domain.DeliveryAttempt) error {
	ret := _m.Called(ctx, eventID, attempt)

	if len(ret) == 0 {
		panic("no return value specified for MarkEventPoison")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.DeliveryAttempt) error); ok {
		r0 = rf(ctx, eventID, attempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkEventPoison_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkEventPoison'
type MockRepository_MarkEventPoison_Call struct {
	*mock.Call
}

// MarkEventPoison is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - attempt domain.DeliveryAttempt
func (_e *MockRepository_Expecter) MarkEventPoison(ctx interface{}, eventID interface{}, attempt interface{}) *MockRepository_MarkEventPoison_Call {
	return &MockRepository_MarkEventPoison_Call{Call: _e.mock.On("MarkEventPoison", ctx, eventID, attempt)}
}

func (_c *MockRepository_MarkEventPoison_Call) Run(run func(ctx context.Context, eventID string, attempt domain.DeliveryAttempt)) *MockRepository_MarkEventPoison_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.DeliveryAttempt))
	})
	return _c
}

func (_c *MockRepository_MarkEventPoison_Call) Return(_a0 error) *MockRepository_MarkEventPoison_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkEventPoison_Call) RunAndReturn(run func(context.Context, string, domain.DeliveryAttempt) error) *MockRepository_MarkEventPoison_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEventAttempt provides a mock function with given fields: ctx, eventID, status, nextRetryAt, attempt
func (_m *MockRepository) UpdateEventAttempt(ctx context.Context, eventID string, status domain.EventStatus, nextRetryAt *time.Time, attempt domain.DeliveryAttempt) error {
	ret := _m.Called(ctx, eventID, status, nextRetryAt, attempt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEventAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.EventStatus, *time.Time, domain.DeliveryAttempt) error); ok {
		r0 = rf(ctx, eventID, status, nextRetryAt, attempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateEventAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEventAttempt'
type MockRepository_UpdateEventAttempt_Call struct {
	*mock.Call
}

// UpdateEventAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - status domain.EventStatus
//   - nextRetryAt *time.Time
//   - attempt domain.DeliveryAttempt
func (_e *MockRepository_Expecter) UpdateEventAttempt(ctx interface{}, eventID interface{}, status interface{}, nextRetryAt interface{}, attempt interface{}) *MockRepository_UpdateEventAttempt_Call {
	return &MockRepository_UpdateEventAttempt_Call{Call: _e.mock.On("UpdateEventAttempt", ctx, eventID, status, nextRetryAt, attempt)}
}

func (_c *MockRepository_UpdateEventAttempt_Call) Run(run func(ctx context.Context, eventID string, status domain.EventStatus, nextRetryAt *time.Time, attempt domain.DeliveryAttempt)) *MockRepository_UpdateEventAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.EventStatus), args[3].(*time.Time), args[4].(domain.DeliveryAttempt))
	})
	return _c
}

func (_c *MockRepository_UpdateEventAttempt_Call) Return(_a0 error) *MockRepository_UpdateEventAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateEventAttempt_Call) RunAndReturn(run func(context.Context, string, domain.EventStatus, *time.Time, domain.DeliveryAttempt) error) *MockRepository_UpdateEventAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
